// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using tmp;

#nullable disable

namespace tmp.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260319074115_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.2");

            modelBuilder.Entity("tmp.Notebook", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("Notebooks");
                });

            modelBuilder.Entity("tmp.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("tmp.Notebook", b =>
                {
                    b.HasOne("tmp.User", "User")
                        .WithOne("Notebook")
                        .HasForeignKey("tmp.Notebook", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("tmp.User", b =>
                {
                    b.Navigation("Notebook");
                });
#pragma warning restore 612, 618
        }
    }
}
